# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# 3.0 notes
# the author field works a bit differently now
#author: Taylor Talkington
#email: "taylor.talkington@gmail.com"
author:
  name: Eric Bell
  email: 

title: Eric Bell
description: > # It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  Holistic product and service design, making complexity feel simple. <a href="/assets/EricBell_Resume_2022.pdf">Resume (PDF)</a>
# email: your-email@example.com

url: "https://ericthebell.github.io" # (optional) https://example.com, defaults to http://localhost:4000 in development
permalink: "/:categories/:title" # how your URLs are built, see https://jekyllrb.com/docs/permalinks/#builtinpermalinkstyles
logo: eric_viki.png

# theme: minima # look for themes on https://github.com/topics/jekyll-theme and https://rubygems.org/search?utf8=%E2%9C%93&query=jekyll-theme
remote_theme: jekyll/minima

header_pages:
  - portfolio.md
  - talks.md
  - about.md

# 3.0 notes
# Also, I can specify the skin now!
minima:
  skin: dark
  date_format: "%Y-%m-%d %H:%M"
  social_links:
    - { platform: linkedin, user_url: "https://linkedin.com/in/ericthebell" }
    - { platform: instagram, user_url: "https://instagram.com/ericthebell" }
    - { platform: mastodon,  user_url: "https://indieweb.social/@ericthebell" }
    - { platform: twitter, user_url: "https://twitter.com/ericthebell" }
    - { platform: github, user_url: "https://github.com/ericthebell" }
    - { platform: pdf, user_url: "assets/EricBell_Resume_2022.pdf"}
    #twitter: ericthebell
    #github: ericthebell
    #instagram: ericthebell
    #linkedin: ericthebell
    #mastodon:
    # - username: ericthebell
    #   instance: indieweb.social
    # rss: rss

google_analytics: G-JL11R2DP8Z

defaults:
  - scope:
      path: "_roles"
      type: "roles"
    values:
      layout: "role"
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: "_talks"
      type: "talks"
    values:
      layout: "talk"

collections: # blog is automatic collection of posts
  roles:
    output: true # collection per job, e.g. Vineti page
  projects:
    output: true # collection per ...?
  talks:
    output: true # collection per talk
  tags: 
    output: true # page for each post, talk, or project tag
    permalink: tags/:path/
    # try https://blog.lunarlogic.io/2019/managing-tags-in-jekyll-blog-easily/
    # or https://jameshfisher.com/2019/05/05/how-can-i-add-tags-to-a-jekyll-blog/
  
# Build settings

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
