# Jekyll main configuration file
# See https://jekyllrb.com/docs/configuration/ to further customize this file
# Defaults settings https://jekyllrb.com/docs/configuration/#default-configuration

title: Eric Bell | UX, product, service design
description: Product & service design to make complexity feel simple

url: # (optional) https://example.com, defaults to http://localhost:4000 in development
permalink: /:categories/:title/ # how your URLs are built, see https://jekyllrb.com/docs/permalinks/#builtinpermalinkstyles
theme: minima # look for themes on https://github.com/topics/jekyll-theme and https://rubygems.org/search?utf8=%E2%9C%93&query=jekyll-theme
# timezone: America/Los_Angeles # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Google Analytics
google_analytics: G-JL11R2DP8Z

collections: # blog is automatic collection of posts
  roles:
    output: true # collection per job, e.g. Vineti page
  talks:
    output: true # collection of all talks

defaults:
  - scope:
      path: ""
      type: "posts" # blog posts
    values:
      layout: "post"
  - scope:
      path: ""
      type: "roles"
    values:
      layout: "role"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "talk"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Filtering Content
show_drafts         : null

# Files to excludes from your website
# exclude:  
# - .gitignore
# - CNAME 
